# Generated by Django 5.1.2 on 2024-10-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_new_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='new_image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='news/'),
        ),
    ]
